name: Documentation Updates

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      docs-tree: ${{ steps.docs-tree.outputs.src }}
    steps:
      - uses: dorny/paths-filter@v2
        id: docs-tree
        with:
          filters: |
            src:
              - 'Documentation/**'
              - 'bugtool/cmd/**'
              - 'cilium/cmd/**'
              - 'cilium-health/cmd/**'
              - 'daemon/cmd/**'
              - 'hubble-relay/cmd/**'
              - 'operator/cmd/**'

  build-html:
    needs: changes
    if: ${{ needs.changes.outputs.docs-tree == 'true' }}
    name: Validate & Build HTML
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: docker://cilium/docs-builder:latest
        with:
          entrypoint: ./Documentation/check-build.sh
          args: html
