name: Documentation Updates

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  check_changes:
    name: Deduce required tests from code changes
    runs-on: ubuntu-latest
    outputs:
      docs-tree: ${{ steps.docs-tree.outputs.src }}
    steps:
      - name: Check code changes
        uses: dorny/paths-filter@v2
        id: docs-tree
        with:
          base: ${{ github.event.pull_request.base.sha || github.event.before }}
          filters: |
            src:
              - 'Documentation/**'
              - 'bugtool/cmd/**'
              - 'cilium/cmd/**'
              - 'cilium-health/cmd/**'
              - 'daemon/cmd/**'
              - 'hubble-relay/cmd/**'
              - 'operator/cmd/**'

  # Runs only if code under Documentation or */cmd/ is changed as the docs
  # should be unaffected otherwise.
  build-html:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.docs-tree == 'true' }}
    name: Validate & Build HTML
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: docker://cilium/docs-builder:latest
        with:
          entrypoint: ./Documentation/check-build.sh
          args: html
